
package com.ejt.demo.server.handlers;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WsHandlerService", targetNamespace = "http://handlers.server.demo.ejt.com/", wsdlLocation = "http://localhost:10091/ws?wsdl")
public class WsHandlerService
    extends Service
{

    private final static URL WSHANDLERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(WsHandlerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = WsHandlerService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:" + WsHandlerImpl.PORT + "/ws?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:" + WsHandlerImpl.PORT + "/ws?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSHANDLERSERVICE_WSDL_LOCATION = url;
    }

    public WsHandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsHandlerService() {
        super(WSHANDLERSERVICE_WSDL_LOCATION, new QName("http://handlers.server.demo.ejt.com/", "WsHandlerService"));
    }

    /**
     * 
     * @return
     *     returns WsHandler
     */
    @WebEndpoint(name = "WsHandlerPort")
    public WsHandler getWsHandlerPort() {
        return super.getPort(new QName("http://handlers.server.demo.ejt.com/", "WsHandlerPort"), WsHandler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsHandler
     */
    @WebEndpoint(name = "WsHandlerPort")
    public WsHandler getWsHandlerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://handlers.server.demo.ejt.com/", "WsHandlerPort"), WsHandler.class, features);
    }

}
